### ISSUE TITLE
NullPointer exception

### ISSUE THREAD

**Issue by marcocevoli** [TeWu/GmailAttachmentsExtractor#4]
First of all, thanks a million for your script. It really helped me clean my inbox.
I've come across this error: https://i.imgur.com/Jxd907C.png
I don't know if the issue is caused by the ampersand and double // in the mail subject, no idea about it. I hope the above screenshot helps you pinpoint the problem. I also understand that it might not be worth investigating. No prob at all.
Cheers,
Marco

**Comment by TeWu** [comment]
Thanks for reporting this.
I suspect it might be caused by emails, that don't have ANY labels applied to them. 
You might be able to avoid the error by applying some label to the email that is causing the error. If you do that It would be helpful if you share the result - is this the way to avoid this error?

**Comment by marcocevoli** [comment]
Yes, I confirm that it's the absence of a label that triggers the error. I had a similar error with another message and applying a label solved it.

**Comment by TeWu** [comment]
Thanks for the feedback.
This bug will be fixed in the next released version (probably next week). Alternatively you can build from source, and have fixed version right now.
