### ISSUE TITLE
Handle exceptions by skipping the message and continuing.

### ISSUE THREAD

**Issue by shyderc** [TeWu/GmailAttachmentsExtractor#8]
In #6 I noted various exceptions.  Can the code handle them by noting them and continuing to the next message?

**Comment by TeWu** [comment]
In my opinion ignoring exceptions/errors is a really bad idea. For example it might lead to a situation where the attachments from the email are correctly downloaded to the disk, but due to a program error, a copy of the email without attachments is not created, and inserted to Gmail. The fact that the attachments have been successfully downloaded may suggest that the email may be safely deleted from Gmail. But this is not true. Since a copy of the email without attachments has never been created, deleting this email from Gmail will cause its TEXT CONTENT (not attachments) to be irretrievably lost. This is only one scenario that could lead to data loss. I can also imagine more scenarios the can lead to other issues, like email duplication. Then, manually solving email duplication involve  deleting emails, and making a mistake in deciding which email to delete can lead to data loss again. 

As You probably can already say, in case of program that could potentially be used to process someone's invaluable data (like business data, family photos etc.), I'm not a big fan of NOT failing fast. On the other hand, this "fail late" behaviour might be useful for debugging purposes - e.g. reporting all errors at once, instead of unnecessarily long sessions of reporting and fixing bugs one at a time. Because there is a good use case for "fail late" behaviour, I've added a `--fail-late` switch (introduced as `--unsafe` in 1eda784, renamed to `--fail-late` in 326d795):

```
--fail-late           If processing email message is unsuccessful (results in an error), ignore that error and
                        proceed to the next email. All ignored errors are listed at the end of the program
                        execution. Running the program with --fail-late switch is STRONGLY DISCOURAGED! Ignoring
                        errors shouldn't cause any immediate problems, but it may confuse You about which actions
                        program performed successfully, and which not, and in result You may get tricked to act
                        in a way that can lead to data loss, email duplication and other unforeseen consequences.
                        Please use --fail-late switch only for debugging purposes, and not to do actual work of
                        extracting attachments.
```

**Comment by TeWu** [comment]
Please note that I renamed `--unsafe` switch to `--fail-late` in 326d795. I've edited the comment above to mention the new name of the switch to not cause misinformation.

Also note, that I've introduced `--unsafe` switch in the same commit, but now that switch is doing something else:
```
--unsafe              Try some unsafe/not fully tested behaviours, to work around some errors. This switch may
                        cause the program to execute without errors, but the results of it's execution are not
                        guaranteed to be correct, and must be manually verified. Running the program with
                        --unsafe switch is STRONGLY DISCOURAGED! If this switch is necessary, then it should be
                        paired with query string that targets a single, problematic email via its Message-ID (e.
                        g. "rfc822msgid:<MESSAGE-ID@gmail.com>").
```
